# Generated by Django 4.1 on 2022-08-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_me', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='about')),
                ('subtitle', models.CharField(max_length=500)),
                ('tw_link', models.URLField()),
                ('fb_link', models.URLField()),
                ('github_link', models.URLField()),
            ],
        ),
    ]
